language: python
python:
  - "2.7"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.6"

#command to install dependencies
install:
  - pip install -r requirements.txt

#command to run tests
script: coverage run --source=. --omit=tests -m unittest discover -s tests

after_success: coveralls
